export default {
    badges: ' Badges',
    badgesText: 'Badges scale to match the size of the immediate parent element by using relative font sizing and em units.',
    stackui: 'Stack UI',
    dashboard: 'Dashboard',
    dashboardSecond: 'Dashboard 2',
    success: 'Success !',
    confirmMailText: ' A email has been send to youremail@domain.com. Please check for an email from company and click on the included link to reset your password.',
    backToHome: ' Back to Home',
    bySuccessive: '2019 © StackUI theme by',
    pagenotFound: 'PAGE NOT FOUND',
    notFoundMsg: "It's looking like you may have taken a wrong turn. Don't worry... it happens to the best of us. "
    + "You might want to check your internet connection. Here's a little tip that might help you get back on track.",
    returnHome: 'Return Home',
    support: 'Support',
    tryRefreshingMsg: 'Why not try refreshing your page? or you can contact',
    internalServer: 'Internal Server Error',
    seeAgain: 'See you again !',
    successfulMsg: 'You are now successfully sign out.',
    backTo: 'Back to',
    logIn: 'Log In',
    resetPassword: 'Reset Password',
    recoverPassword: 'RECOVER PASSWORD',
    enterEmailText: " Enter your email address and we'll send you an email with instructions to reset your password.",
    dontHaveAccount: "Don't have an account?",
    signUp: 'Sign Up',
    forgetPassword: 'Forgot your password?',
    signInwith: 'Sign in with',
    invalid: 'invalid password',
    invalidUser: 'invalid Username',
    enterEmailPassword: ' Enter your email address and password to access admin panel.',
    dontHaveAccountCreateNow: "Don't have an account? Create your free account now",
    createAccount: 'CREATE ACCOUNT',
    alreadyAccount: 'Already have account?',
    signUsing: 'Sign up using',
    transactionHistory: 'Transaction History',
    earningReport: 'Earning Reports',

  };
  