export default {
 pillBadge: 'Pill Badges',
 makeBadgeRounded : ' Use the pill modifier props to make badges more rounded.',   
 primary: '  Primary',
secondary: 'Secondary',
success: 'Success',
danger: 'Danger',
warning: 'Warning',
info: 'Info',
light: 'Light',
dark: 'Dark',
exaplHeading: 'Example heading',
new: 'New',
pagination:'Pagination',
paginationLinkText: 'Provide pagination links for your site or app with the multi-page pagination component.',
breadcrumb: 'Breadcrumb',
indicateNavigation: 'Indicate the current page’s location within a navigational hierarchy.',
home: 'Home',
data: 'Data',
library: 'Library',
setting: "Settings",
message: 'Messages',
balance: 'Balance',
num: ' 8504',
badgeNum: '25',

}